PCS/Controllers/HomeBackController.cs
using PCS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace PCS.Controllers
{
    [SessionTimeout]
    public class SessionTimeoutAttribute : ActionFilterAttribute
    {
        public override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            HttpContext ctx = HttpContext.Current;
            if (HttpContext.Current.Session["UserID"] == null)
            {
                filterContext.Result = new RedirectResult("~/Home/Login");
                return;
            }
            base.OnActionExecuting(filterContext);
        }
    }
    public class HomeBackController : Controller
    {
        private ApplicationDbContext _context;

        public HomeBackController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: HomeBack
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string username,string pass)
        {
            string dir = "";
            if (ModelState.IsValid)
            {
                var obj = _context.Database.SqlQuery<UserLogin>("SELECT * FROM UserLogins WHERE UserName='" + username + "' AND Pass ='" + pass + "' ").FirstOrDefault();
                if (obj != null)
                {
                    Session["UserID"] = obj.id;
                    Session["UserName"] = obj.UserName.ToString();
                    dir = "Index";
                }
                else
                {
                    TempData["Invalid"] = "Invalid Login Details";
                    dir = "Login";
                }
            }
            return RedirectToAction(dir);
        }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult LogOut()
        {
            Session["UserID"] = null;
            FormsAuthentication.SignOut();
            Session.Clear();
            Session.RemoveAll();
            Session.Abandon();

            return RedirectToAction("Index","Main");
        }
    }
}

PCS/Controllers/RegisterController.cs
using PCS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PCS.Controllers
{
    public class RegisterController : Controller
    {
        private ApplicationDbContext _context;

        public RegisterController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Register
        public ActionResult Index(Registration Registration)
        {
            Registration.fee = 0;
            Registration.Hotel = 0;
            Registration.Total = 0;
            return View(Registration);
        }
        public ActionResult All()
        {
            var List = _context.Registration.ToList();
            return View(List);
        }
        [HttpPost]
        public ActionResult Save(Registration Registration)
        {
            _context.Registration.Add(Registration);
            _context.SaveChanges();
            TempData["Insert"] = "Submitted Successfully...";
            return RedirectToAction("Index");
        }
        public ActionResult Report(int id)
        {
            var list = _context.Registration.SingleOrDefault(c=>c.id == id);
            return View(list);
        }
    }
}

PCS/Controllers/SessionsController.cs
using PCS.Models;
using PCS.Models.Views;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PCS.Controllers
{
    [ValidateInput(false)]
    public class SessionsController : Controller
    {
        private ApplicationDbContext _context;
        public SessionsController()
        {
            _context = new ApplicationDbContext();
        }
        // GET: Sessions
        public ActionResult Index()
        {
            var List = _context.Session.ToList();
            return View(List);
        }
        public ActionResult Create(Session Session)
        {
            return View(Session);
        }
        [HttpPost]
        public ActionResult Save(Session Session)
        {
            string d = "";
            if (Session.id == 0) 
            {
                _context.Session.Add(Session);
                d = "Create";
            }
            else
            {
                var db = _context.Session.SingleOrDefault(c => c.id == Session.id);
                db.Name = Session.Name;
                db.Desc = Session.Desc;
                d = "Index";
            }
            _context.SaveChanges();
            return RedirectToAction(d);
        }
        public ActionResult Edit(int id)
        {
            var db = _context.Session.SingleOrDefault(c => c.id == id);
            return View("Create",db);
        }
    }
}

PCS/Views/Shared/_Back.cshtml
<!DOCTYPE html>
<html lang="zxx">

<head>
    <!-- meta tag -->
    <meta charset="utf-8">
    <title>PCS</title>
    <meta name="description" content="">
    <!-- responsive tag -->
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- favicon -->
    <link rel="apple-touch-icon" href="apple-touch-icon.html">
    <link rel="shortcut icon" type="image/x-icon" href="~/Content/assets/images/fav.png">

    <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Playfair+Display" />
    <!--Databa-->
    <link href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap.min.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#My').DataTable();
            $('#You').DataTable();
        });
    </script>
    <!-- Bootstrap v4.4.1 css -->
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- font-awesome css -->
    <link rel="stylesheet" type="text/css" href="~/Content/assets/css/font-awesome.min.css">
    <!-- animate css -->
    <link rel="stylesheet" type="text/css" href="~/Content/assets/css/animate.css">
    <!-- aos css -->
    <link rel="stylesheet" type="text/css" href="~/Content/assets/css/aos.css">
    <!-- owl.carousel css -->
    <link rel="stylesheet" type="text/css" href="~/Content/assets/css/owl.carousel.css">
    <!-- slick css -->
    <link rel="stylesheet" type="text/css" href="~/Content/assets/css/slick.css">
    <!-- off canvas css -->
    <link rel="stylesheet" type="text/css" href="~/Content/assets/css/off-canvas.css">
    <!-- linea-font css -->
    <link rel="stylesheet" type="text/css" href="~/Content/assets/fonts/linea-fonts.css">
    <!-- flaticon css  -->
    <link rel="stylesheet" type="text/css" href="~/Content/assets/fonts/flaticon.css">
    <!-- magnific popup css -->
    <link rel="stylesheet" type="text/css" href="~/Content/assets/css/magnific-popup.css">
    <!-- Main Menu css -->
    <link rel="stylesheet" href="~/Content/assets/css/rsmenu-main.css">
    <!-- nivo slider CSS -->
    <link rel="stylesheet" type="text/css" href="~/Content/assets/inc/custom-slider/css/nivo-slider.css">
    <link rel="stylesheet" type="text/css" href="~/Content/assets/inc/custom-slider/css/preview.css">
    <!-- rsmenu transitions css -->
    <link rel="stylesheet" href="~/Content/assets/css/rsmenu-transitions.css">
    <!-- spacing css -->
    <link rel="stylesheet" type="text/css" href="~/Content/assets/css/rs-spacing.css">
    <!-- style css -->
    <link rel="stylesheet" type="text/css" href="~/Content/style.css"> <!-- This stylesheet dynamically changed from style.less -->
    <!-- responsive css -->
    <link rel="stylesheet" type="text/css" href="~/Content/assets/css/responsive.css">

    <style>
        .responsive-iframe {
            position: absolute;
            top: 0;
            left: 0;
            bottom: 0;
            right: 0;
            width: 100%;
            height: 100%;
        }

        .fn {
            font-size: 12px;
        }
    </style>
</head>
<body class="defult-home">

    <!-- Preloader area start here -->
    <div id="loader" class="loader">
        <div class="spinner"></div>
    </div>
    <!--End preloader here -->
    <!--Full width header Start-->
    <div class="full-width-header">
        <!-- Toolbar Start -->
        <div class="toolbar-area hidden-md">
            <div class="container">
                <div class="row">
                    <div class="col-md-7">
                        <div class="toolbar-contact">
                            <ul>
                                <li><i class="flaticon-user"></i><a href="#">@Session["UserName"]</a></li>
                                <li><i class="fa fa-home"></i><a href="@Url.Action("Index","HomeBack")">Home</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-5">
                        <div class="toolbar-sl-share">
                            <ul>
                                @*<li class="opening"> <i class="flaticon-clock"></i> Mon - Fri: 9:00 am - 06.00pm / Closed on Weekends</li>*@
                                <li class="pull-right"><a href="@Url.Action("LogOut","HomeBack")"><img src="~/Content/Login.png" alt="" style="width:40px" /></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Toolbar End -->
        <!--Header Start-->
        <header id="rs-header" class="rs-header">
            <!-- Menu Start -->
            <div class="menu-area menu-sticky">
                <div class="container">
                    <div class="row">
                        <div class="col-lg-12" style="margin-top:-17px">
                            <div class="rs-menu-area">
                                <div class="main-menu">
                                    <div class="mobile-menu">
                                        <a class="rs-menu-toggle">
                                            <i class="fa fa-bars"></i>
                                        </a>
                                    </div>
                                    <nav class="rs-menu pr-65">
                                        <ul id="onepage-menu" class="nav-menu">
                                            <li><a href="@Url.Action("All","Register")">Registerd Peopels</a></li>
                                            <li><a href="@Url.Action("Index","Sessions")">Scientific Sessions</a></li>
                                        </ul> <!-- //.nav-menu -->
                                    </nav>
                                </div> <!-- //.main-menu -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Menu End -->
            <!-- Canvas Menu start -->
            <!-- Canvas Menu end -->
        </header>
        <!--Header End-->
    </div>
    <!--Full width header End-->
    <div class="main-content"style="height:500px">
        @RenderBody()
    </div>
    

    <!-- Footer Start -->
    @*<footer id="rs-footer" class="rs-footer">
        <div class="container">
            <div class="footer-bottom">
                <div class="row y-middle">
                    <div class="col-lg-6 col-md-8 sm-mb-21">
                        <div class="copyright">
                            <p>© Copyright 2021 Cardiology. All Rights Reserved.</p>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-4 text-right sm-text-center">
                        <ul class="footer-social">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>*@
    <!-- Footer End -->
    <!-- start scrollUp  -->
    <div id="scrollUp">
        <i class="fa fa-angle-up"></i>
    </div>
    <!-- End scrollUp  -->
    <!-- Search Modal Start -->
    <div aria-hidden="true" class="modal fade search-modal" role="dialog" tabindex="-1">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span class="flaticon-cross"></span>
        </button>
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="search-block clearfix">
                    <form>
                        <div class="form-group">
                            <input class="form-control" placeholder="Search Here..." type="text" required="">
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- Search Modal End -->
    <!-- modernizr js -->
    @*<script src="~/Content/assets/js/modernizr-2.8.3.min.js"></script>*@
    <!-- jquery latest version -->
    @*<script src="~/Content/assets/js/jquery.min.js"></script>*@
    <!-- Bootstrap v4.4.1 js -->
    @*<script src="~/Content/assets/js/bootstrap.min.js"></script>*@
    <!-- Menu js -->
    <script src="~/Content/assets/js/rsmenu-main.js"></script>
    <!-- op nav js -->
    <script src="~/Content/assets/js/jquery.nav.js"></script>
    <!-- owl.carousel js -->
    <script src="~/Content/assets/js/owl.carousel.min.js"></script>
    <!-- Slick js -->
    <script src="~/Content/assets/js/slick.min.js"></script>
    <!-- isotope.pkgd.min js -->
    <script src="~/Content/assets/js/isotope.pkgd.min.js"></script>
    <!-- imagesloaded.pkgd.min js -->
    <script src="~/Content/assets/js/imagesloaded.pkgd.min.js"></script>
    <!-- wow js -->
    <script src="~/Content/assets/js/wow.min.js"></script>
    <!-- aos js -->
    <script src="~/Content/assets/js/aos.js"></script>


    <!-- Skill bar js -->
    <script src="~/Content/assets/js/skill.bars.jquery.js"></script>
    <script src="~/Content/assets/js/jquery.counterup.min.js"></script>
    <!-- counter top js -->
    <script src="~/Content/assets/js/waypoints.min.js"></script>
    <!-- video js -->
    <script src="~/Content/assets/js/jquery.mb.YTPlayer.min.js"></script>
    <!-- magnific popup js -->
    <script src="~/Content/assets/js/jquery.magnific-popup.min.js"></script>

    <!-- Nivo slider js -->
    <script src="~/Content/assets/inc/custom-slider/js/jquery.nivo.slider.js"></script>
    <!-- plugins js -->
    <script src="~/Content/assets/js/plugins.js"></script>
    <!-- contact form js -->
    <script src="~/Content/assets/js/contact.form.js"></script>
    <!-- main js -->
    <script src="~/Content/assets/js/main.js"></script>
</body>


</html>